### ISSUE TITLE
Reverse numbering citations in CV?

### ISSUE THREAD

**Issue by chchang47** [robjhyndman/CV#3]
Thank you Prof @robjhyndman for open-sourcing your CV style file! It is really great to be able to use your CV style file, and I really appreciate the `\addtocategory{...}` function. Sorry to impose, but I cannot figure out if (and how) it would be possible to reverse order citations in each `bibcategory`. I've tried modifying `\def\lastref#1{\addtocounter{#1}{\value{papers}}\setcounter{papers}{0}}`and some of the other `\addtocounter` commands that I saw in the style file, but I unfortunately got nowhere. Any insight appreciated! I also looked into StackOverflow (e.g. [here](https://tex.stackexchange.com/questions/21401/biblatex-reverse-numbering-i-e-count-down) and [here](https://tex.stackexchange.com/questions/58642/bibtex-reverse-numbering)) but I couldn't figure out how to work in those suggestions to your style file (assuming that those approaches would even work ... which I also can't figure out). Thanks in advance for your time!

**Comment by robjhyndman** [comment]
If you just want to change the ordering of citations, this is now handled by dplyr. See https://blog.mitchelloharawild.com/blog/vitae-0-2-0/

The numbering of citations is a different issue and much harder. It would require a modification of cv.sty along the lines of the stackoverflow links you provided, and that is not something I have time to do right now.

**Comment by chchang47** [comment]
Great, thanks Prof. @robjhyndman! I hadn't thought to use a Rmarkdown + TeX workflow, but I'll look into it! Appreciate your time and generosity.
