### ISSUE TITLE
Citation style (CSL) for this CV

### ISSUE THREAD

**Issue by mitchelloharawild** [robjhyndman/CV#5]
`vitae` now uses CSL files to format CV bibliographies. I've spent a bit of time creating a CSL for the current vitae style, and apart from minor styling changes (spacing, indentation, etc) this is now done.

However before I finish with the style changes, I figured I should ask if you knew of a CSL that would be better suited for this CV (and perhaps as a default for `vitae`).

**Comment by robjhyndman** [comment]
The ASA style is close: https://github.com/citation-style-language/styles/blob/master/american-statistical-association.csl
But I prefer mine. :)

**Comment by mitchelloharawild** [comment]
Looks like pandoc can't handle CSL whitespace, so I don't think properly handling citation number indentation is possible yet (https://github.com/jgm/pandoc/issues/335).

Do you think the `citation-number` is important, or the alignment?

**Comment by abhijitsharma111** [comment]
Hi I think citation number is very useful for a CV. Thanks again.
